package template

// ResponsiveCSS is the framework-level mobile pass for the three-column
// #left-side / #main / #right-side layout that template.Page emits.
//
// Why it lives here and not in each site's stylus build: the column layout is
// generated by this package, so its small-screen behavior is a framework
// concern. Sites (cema, ccswm) style the columns for desktop in their own
// app.css; this block only overrides the metrics that break phones. Inlining
// it after the app.css <link> (same slot as grid.CSS) means it wins the
// cascade without a site rebuild, and every site gets the fix at once.
//
// The site frame is: fixed banner + fixed menu above, fixed footer below, and
// #mid as the lone scroll container sized calc(100vh - chrome) with
// overflow-y:auto. We deliberately KEEP that frame — heights, margin-top and
// the fixed chrome are per-site values we can't know here — and only restack
// the columns inside the scroller:
//
//	Desktop (from site app.css)         Mobile (this block)
//	┌─────────┬──────────┬─────────┐    ┌───────────────────┐
//	│ #left   │  #main   │ #right  │    │       #main       │  <- order:-1
//	│ (float, │ (float,  │ (float, │ →  ├───────────────────┤
//	│  22%)   │  ~56%)   │  22%)   │    │     #left-side    │
//	└─────────┴──────────┴─────────┘    ├───────────────────┤
//	                                    │    #right-side    │
//	                                    └───────────────────┘
//
// Design choices, in order of impact:
//   - min-width:0 on #mid: sites set min-width:800px, which alone forces
//     horizontal panning on every phone even with the viewport meta present.
//   - flex-column instead of clearing floats: flex `order` lets the main
//     content render first when stacked (sidebars are secondary widgets),
//     which float clearing cannot do without moving DOM nodes.
//   - Children keep their own display value: layouts like "main only" hide
//     unused sidebars via display:none in site CSS; we never set display on
//     the children so those rules keep working.
//   - !important throughout: the site rules are id+class selectors compiled
//     from stylus; this block must beat them regardless of each site's exact
//     specificity, and it is scoped to one breakpoint so the blast radius is
//     contained.
//
// 768px matches the point where two 180px-min sidebars plus a readable main
// column no longer fit; the event form's own 640px query (the original
// responsive pattern in this codebase) is for a single form grid and remains
// independent.
const ResponsiveCSS = `
@media (max-width: 768px) {
  #mid {
    min-width: 0 !important;
    width: 100% !important;
    display: flex !important;
    flex-direction: column !important;
  }
  #mid > #left-side,
  #mid > #main,
  #mid > #right-side {
    float: none !important;
    width: auto !important;
    min-width: 0 !important;
    max-width: none !important;
    height: auto !important;
    min-height: 0 !important;
    overflow: visible !important;
    box-shadow: none !important;
    margin-left: 0 !important;
    margin-right: 0 !important;
  }
  /* Main content first when stacked; sidebars follow in DOM order. */
  #mid > #main { order: -1; }
}
`
