//+build ignore

package main

import (
	"fmt"
	"os"
)

const initialTemplate = `
// Code generated by go generate; DO NOT EDIT.

package packed
`

func main() {
	fmt.Println("Called from go generate.")
	fmt.Println("Here I would pack things...")

	// Find our location
	finfo, err := os.Stat("pack/packed/module_payment_form.go")
	if err != nil { fmt.Println(err); return }
	fmt.Println(finfo.Name(), finfo.Size())

	// For each file of allowed extension in pack/src
		// Read file with bufio.Scanner
		// Look for a line starting with // ROPACKER START
		// Get the var name from the above line
		// Read all other lines till // ROPACKER END
		// Append to the basic template:
		//	var <NAME> = `<Other lines read>` (escape backticks in Other lines)
}
