// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

var TableNames = struct {
	Articles       string
	Events         string
	GooseDBVersion string
	Images         string
	MenuDefs       string
	Pages          string
	Sermons        string
	Users          string
}{
	Articles:       "articles",
	Events:         "events",
	GooseDBVersion: "goose_db_version",
	Images:         "images",
	MenuDefs:       "menu_defs",
	Pages:          "pages",
	Sermons:        "sermons",
	Users:          "users",
}
