// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// MenuDef is an object representing the database table.
type MenuDef struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	UpdatedBy string    `boil:"updated_by" json:"updated_by" toml:"updated_by" yaml:"updated_by"`
	Title     string    `boil:"title" json:"title" toml:"title" yaml:"title"`
	Slug      string    `boil:"slug" json:"slug" toml:"slug" yaml:"slug"`
	Published bool      `boil:"published" json:"published" toml:"published" yaml:"published"`
	IsAdmin   bool      `boil:"is_admin" json:"is_admin" toml:"is_admin" yaml:"is_admin"`
	Items     null.JSON `boil:"items" json:"items,omitempty" toml:"items" yaml:"items,omitempty"`

	R *menuDefR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L menuDefL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MenuDefColumns = struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	UpdatedBy string
	Title     string
	Slug      string
	Published string
	IsAdmin   string
	Items     string
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	UpdatedBy: "updated_by",
	Title:     "title",
	Slug:      "slug",
	Published: "published",
	IsAdmin:   "is_admin",
	Items:     "items",
}

// menuDefR is where relationships are stored.
type menuDefR struct {
}

// menuDefL is where Load methods for each relationship are stored.
type menuDefL struct{}

var (
	menuDefColumns               = []string{"id", "created_at", "updated_at", "updated_by", "title", "slug", "published", "is_admin", "items"}
	menuDefColumnsWithoutDefault = []string{"created_at", "updated_at", "updated_by", "title", "slug", "published", "is_admin", "items"}
	menuDefColumnsWithDefault    = []string{"id"}
	menuDefPrimaryKeyColumns     = []string{"id"}
)

type (
	// MenuDefSlice is an alias for a slice of pointers to MenuDef.
	// This should generally be used opposed to []MenuDef.
	MenuDefSlice []*MenuDef
	// MenuDefHook is the signature for custom MenuDef hook methods
	MenuDefHook func(boil.Executor, *MenuDef) error

	menuDefQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	menuDefType                 = reflect.TypeOf(&MenuDef{})
	menuDefMapping              = queries.MakeStructMapping(menuDefType)
	menuDefPrimaryKeyMapping, _ = queries.BindMapping(menuDefType, menuDefMapping, menuDefPrimaryKeyColumns)
	menuDefInsertCacheMut       sync.RWMutex
	menuDefInsertCache          = make(map[string]insertCache)
	menuDefUpdateCacheMut       sync.RWMutex
	menuDefUpdateCache          = make(map[string]updateCache)
	menuDefUpsertCacheMut       sync.RWMutex
	menuDefUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var menuDefBeforeInsertHooks []MenuDefHook
var menuDefBeforeUpdateHooks []MenuDefHook
var menuDefBeforeDeleteHooks []MenuDefHook
var menuDefBeforeUpsertHooks []MenuDefHook

var menuDefAfterInsertHooks []MenuDefHook
var menuDefAfterSelectHooks []MenuDefHook
var menuDefAfterUpdateHooks []MenuDefHook
var menuDefAfterDeleteHooks []MenuDefHook
var menuDefAfterUpsertHooks []MenuDefHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MenuDef) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range menuDefBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MenuDef) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range menuDefBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MenuDef) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range menuDefBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MenuDef) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range menuDefBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MenuDef) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range menuDefAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MenuDef) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range menuDefAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MenuDef) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range menuDefAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MenuDef) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range menuDefAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MenuDef) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range menuDefAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMenuDefHook registers your hook function for all future operations.
func AddMenuDefHook(hookPoint boil.HookPoint, menuDefHook MenuDefHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		menuDefBeforeInsertHooks = append(menuDefBeforeInsertHooks, menuDefHook)
	case boil.BeforeUpdateHook:
		menuDefBeforeUpdateHooks = append(menuDefBeforeUpdateHooks, menuDefHook)
	case boil.BeforeDeleteHook:
		menuDefBeforeDeleteHooks = append(menuDefBeforeDeleteHooks, menuDefHook)
	case boil.BeforeUpsertHook:
		menuDefBeforeUpsertHooks = append(menuDefBeforeUpsertHooks, menuDefHook)
	case boil.AfterInsertHook:
		menuDefAfterInsertHooks = append(menuDefAfterInsertHooks, menuDefHook)
	case boil.AfterSelectHook:
		menuDefAfterSelectHooks = append(menuDefAfterSelectHooks, menuDefHook)
	case boil.AfterUpdateHook:
		menuDefAfterUpdateHooks = append(menuDefAfterUpdateHooks, menuDefHook)
	case boil.AfterDeleteHook:
		menuDefAfterDeleteHooks = append(menuDefAfterDeleteHooks, menuDefHook)
	case boil.AfterUpsertHook:
		menuDefAfterUpsertHooks = append(menuDefAfterUpsertHooks, menuDefHook)
	}
}

// OneP returns a single menuDef record from the query, and panics on error.
func (q menuDefQuery) OneP() *MenuDef {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single menuDef record from the query.
func (q menuDefQuery) One() (*MenuDef, error) {
	o := &MenuDef{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for menu_defs")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all MenuDef records from the query, and panics on error.
func (q menuDefQuery) AllP() MenuDefSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all MenuDef records from the query.
func (q menuDefQuery) All() (MenuDefSlice, error) {
	var o []*MenuDef

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MenuDef slice")
	}

	if len(menuDefAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all MenuDef records in the query, and panics on error.
func (q menuDefQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all MenuDef records in the query.
func (q menuDefQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count menu_defs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q menuDefQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q menuDefQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if menu_defs exists")
	}

	return count > 0, nil
}

// MenuDefsG retrieves all records.
func MenuDefsG(mods ...qm.QueryMod) menuDefQuery {
	return MenuDefs(boil.GetDB(), mods...)
}

// MenuDefs retrieves all the records using an executor.
func MenuDefs(exec boil.Executor, mods ...qm.QueryMod) menuDefQuery {
	mods = append(mods, qm.From("\"menu_defs\""))
	return menuDefQuery{NewQuery(exec, mods...)}
}

// FindMenuDefG retrieves a single record by ID.
func FindMenuDefG(id int64, selectCols ...string) (*MenuDef, error) {
	return FindMenuDef(boil.GetDB(), id, selectCols...)
}

// FindMenuDefGP retrieves a single record by ID, and panics on error.
func FindMenuDefGP(id int64, selectCols ...string) *MenuDef {
	retobj, err := FindMenuDef(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindMenuDef retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMenuDef(exec boil.Executor, id int64, selectCols ...string) (*MenuDef, error) {
	menuDefObj := &MenuDef{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"menu_defs\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(menuDefObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from menu_defs")
	}

	return menuDefObj, nil
}

// FindMenuDefP retrieves a single record by ID with an executor, and panics on error.
func FindMenuDefP(exec boil.Executor, id int64, selectCols ...string) *MenuDef {
	retobj, err := FindMenuDef(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *MenuDef) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *MenuDef) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *MenuDef) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *MenuDef) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no menu_defs provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.Time.IsZero() {
		o.UpdatedAt.Time = currTime
		o.UpdatedAt.Valid = true
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(menuDefColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	menuDefInsertCacheMut.RLock()
	cache, cached := menuDefInsertCache[key]
	menuDefInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			menuDefColumns,
			menuDefColumnsWithDefault,
			menuDefColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(menuDefType, menuDefMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(menuDefType, menuDefMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"menu_defs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"menu_defs\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into menu_defs")
	}

	if !cached {
		menuDefInsertCacheMut.Lock()
		menuDefInsertCache[key] = cache
		menuDefInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single MenuDef record. See Update for
// whitelist behavior description.
func (o *MenuDef) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single MenuDef record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *MenuDef) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the MenuDef, and panics on error.
// See Update for whitelist behavior description.
func (o *MenuDef) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the MenuDef.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *MenuDef) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	menuDefUpdateCacheMut.RLock()
	cache, cached := menuDefUpdateCache[key]
	menuDefUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			menuDefColumns,
			menuDefPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update menu_defs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"menu_defs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, menuDefPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(menuDefType, menuDefMapping, append(wl, menuDefPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update menu_defs row")
	}

	if !cached {
		menuDefUpdateCacheMut.Lock()
		menuDefUpdateCache[key] = cache
		menuDefUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q menuDefQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q menuDefQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for menu_defs")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o MenuDefSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o MenuDefSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o MenuDefSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MenuDefSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), menuDefPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"menu_defs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, menuDefPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in menuDef slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *MenuDef) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *MenuDef) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *MenuDef) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *MenuDef) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no menu_defs provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(menuDefColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	menuDefUpsertCacheMut.RLock()
	cache, cached := menuDefUpsertCache[key]
	menuDefUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			menuDefColumns,
			menuDefColumnsWithDefault,
			menuDefColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			menuDefColumns,
			menuDefPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert menu_defs, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(menuDefPrimaryKeyColumns))
			copy(conflict, menuDefPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"menu_defs\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(menuDefType, menuDefMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(menuDefType, menuDefMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert menu_defs")
	}

	if !cached {
		menuDefUpsertCacheMut.Lock()
		menuDefUpsertCache[key] = cache
		menuDefUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single MenuDef record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *MenuDef) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single MenuDef record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *MenuDef) DeleteG() error {
	if o == nil {
		return errors.New("models: no MenuDef provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single MenuDef record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *MenuDef) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single MenuDef record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MenuDef) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no MenuDef provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), menuDefPrimaryKeyMapping)
	sql := "DELETE FROM \"menu_defs\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from menu_defs")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q menuDefQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q menuDefQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no menuDefQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from menu_defs")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o MenuDefSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o MenuDefSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no MenuDef slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o MenuDefSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MenuDefSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no MenuDef slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(menuDefBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), menuDefPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"menu_defs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, menuDefPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from menuDef slice")
	}

	if len(menuDefAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *MenuDef) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *MenuDef) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *MenuDef) ReloadG() error {
	if o == nil {
		return errors.New("models: no MenuDef provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MenuDef) Reload(exec boil.Executor) error {
	ret, err := FindMenuDef(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *MenuDefSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *MenuDefSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MenuDefSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty MenuDefSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MenuDefSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	menuDefs := MenuDefSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), menuDefPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"menu_defs\".* FROM \"menu_defs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, menuDefPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&menuDefs)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MenuDefSlice")
	}

	*o = menuDefs

	return nil
}

// MenuDefExists checks if the MenuDef row exists.
func MenuDefExists(exec boil.Executor, id int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"menu_defs\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if menu_defs exists")
	}

	return exists, nil
}

// MenuDefExistsG checks if the MenuDef row exists.
func MenuDefExistsG(id int64) (bool, error) {
	return MenuDefExists(boil.GetDB(), id)
}

// MenuDefExistsGP checks if the MenuDef row exists. Panics on error.
func MenuDefExistsGP(id int64) bool {
	e, err := MenuDefExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// MenuDefExistsP checks if the MenuDef row exists. Panics on error.
func MenuDefExistsP(exec boil.Executor, id int64) bool {
	e, err := MenuDefExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
